language: node_js
node_js:
  - "8"
git:
  depth: 30
cache: yarn
script:
  # - yarn test
  - if [[ $TRAVIS_COMMIT_MESSAGE != *"skip test"* ]]; then yarn test ; fi ;
  # - [[ $TRAVIS_COMMIT_MESSAGE != *"skip test"* ]] && yarn test;
  # - [ "${TRAVIS_PULL_REQUEST}" = "false" ] &&

